= Deprecation Announcement

We would like to inform our users that the functionality provided by this Identity Provider has been fully integrated into version 3.0.0 of the https://github.com/enonic/app-oidc-idprovider[OIDC ID Provider]. This integration streamlines our services and enhances security and usability.

What This Means for You:

* *Upgrading:* We encourage users of the current IDP to transition to the OIDC ID Provider version 3.0.0. This upgrade ensures continued support and access to the latest features and security improvements.

* *End of Support:* We no longer support this IDP. Users are urged to transition to the OIDC ID Provider version 3.0.0 to ensure continued service and access to the latest features and security improvements.

= Open ID Connect JWT ID Provider

Authenticate your users with JWT tokens issued by a OIDC provider.

This ID provider validates signatures of JWT tokens passed in requests. It does this by calling the well-know endpoint of a OIDC provider to fetch public keys and those keys are then used to validate. It is compatible with all OIDC providers that provide a `jwks_uri` in their well-known configuration.

== Passing tokens to the ID provider

.You can pass tokens to this ID provider in the following way:
* Setting the authorization header: `Authorization: Bearer <TOKEN>`
* Setting a query parameter (if enabled): `https://<HOST>/my/path?jwt=<TOKEN>`
* Setting the Sec-WebSocket-Protocol header (if enabled): `Sec-WebSocket-Protocol: <WS_PROTOCOL>, <TOKEN>`. This is useful for web sockets, i.e `new WebSocket('wss://<HOST>/my/path', [<WS_PROTOCOL>, <TOKEN>]`.

== Compatibility

[cols="1,1,3", options="header"]
|===
|Version
|XP Version
|Download

|1.0.0
|>= 7.3.0
|Not Available

|===

== Build

To build this project, execute the following:

[source,bash]
----
./gradlew clean build
----

== link:docs/index.adoc[Documentation]
